const ShopActionTypes = {
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILUARE : 'FETCH_COLLECTIONS_FAILUARE'
}

export default ShopActionTypes;